/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef identity_CONSTANTS_H
#define identity_CONSTANTS_H

#include "identity_types.h"



class identityConstants {
 public:
  identityConstants();

};

extern const identityConstants g_identity_constants;



#endif
