/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tis_CONSTANTS_H
#define tis_CONSTANTS_H

#include "tis_types.h"



class tisConstants {
 public:
  tisConstants();

};

extern const tisConstants g_tis_constants;



#endif
